### ISSUE TITLE
tests fail due to hardcoded user array

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Impersonate#5]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Impersonate is depending on internal array for User object instead of the factory/similar, causing the test to fail if there are incompatible changes to the user array (f.e. an extra required/unique-constrained field)

### Steps to Reproduce
1. Modify user table (in a migration) with an extra unique-constrained field
2. Run tests

### Expected behavior

Tests to pass as long as the internal logic works (website works fine)

### Actual behavior

Tests fail due to hardcoded user _model_ (array)

`ImpersonateTest.php`'s private `createUser` function is causing this

**Comment by aocneanu** [comment]
He's got a point, @y0net ...
